  # data source config




  spring:
    config:
      import: optional:dotenv:.env
    datasource:
      url: jdbc:postgresql://${DB_HOST_ADDRESS}:${DB_PORT}/${DB_NAME}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

    mail:
      host: smtp.gmail.com
      port: ${SMTP_PORT}
      username: ${SMTP_EMAIL}
      password: ${SMTP_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
